import styled from 'styled-components';
import Link from 'next/link';

export const FooterContainer = styled.footer``;
export const FooterContent = styled.div``;
export const FooterRow = styled.div``;
export const FooterColumn = styled.div``;
export const LogoSection = styled.div``;
export const PaymentSection = styled.div``;
export const PaymentTitle = styled.h5``;
export const PaymentIcons = styled.div``;
export const MenuSection = styled.div``;
export const MenuTitle = styled.h5``;
export const MenuList = styled.ul``;
export const MenuItem = styled.li``;
export const ContactSection = styled.div``;
export const ContactTitle = styled.h5``;
export const ContactList = styled.ul``;
export const ContactItem = styled.li``;
export const SocialLinks = styled.div``;
export const SecuritySection = styled.div``;
export const SecurityTitle = styled.h5``;
export const CopyrightSection = styled.div``;
export const CopyrightContainer = styled.div``;
export const CopyrightRow = styled.div``;
export const CopyrightContent = styled.div``;
export const CopyrightText = styled.p``;
export const CookiesSection = styled.div``;
export const CookiesContent = styled.div``;
export const CookiesText = styled.p``;
export const CookiesButtonGroup = styled.div``;

// Additional styled components
export const LogoLink = styled(Link)``;
export const PaymentIcon = styled.i``;
export const MenuLink = styled(Link)``;
export const ContactIcon = styled.i``;
export const ContactStrong = styled.strong``;
export const ContactLink = styled.a``;
export const SecurityWrapper = styled.div``;
export const SecurityCard = styled.div``;
export const SecurityIcon = styled.i``;
export const SecurityLabel = styled.span``;
export const CopyrightWrapper = styled.div``;
export const CopyrightSpan = styled.span``;
export const CopyrightIcon = styled.i``;
export const CookiesWrapper = styled.div``;
export const CookiesLink = styled(Link)``;
export const CookiesButton = styled.button``;